export const typeColors: Record<string, string> = {
  Fire: '#f5576c',
  Water: '#4facfe',
  Grass: '#43e97b',
  Electric: '#fceabb',
  Ice: '#a1c4fd',
  Rock: '#d7ccc8',
  Ground: '#e4a663',
  Psychic: '#ff9a8b',
  Fairy: '#fbc2eb',
  Bug: '#c0e218',
  Poison: '#bc6ff1',
  Flying: '#89f7fe',
  Dragon: '#8e2de2',
  Dark: '#4b4b4b',
  Steel: '#cfd8dc',
  Ghost: '#5c6bc0',
  Normal: '#e0e0e0',
  Fighting: '#ef6c00',
};

export const typeIcons: Record<string, string> = {
  Fire: '🔥',
  Water: '💧',
  Grass: '🍃',
  Electric: '⚡',
  Ice: '❄️',
  Rock: '🪨',
  Ground: '🌍',
  Psychic: '🧠',
  Fairy: '✨',
  Bug: '🐛',
  Poison: '☠️',
  Flying: '🕊️',
  Dragon: '🐉',
  Dark: '🌑',
  Steel: '⚙️',
  Ghost: '👻',
  Normal: '🔘',
  Fighting: '🥊',
};
